name: Pulumi Deployment
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Use Node.js 16
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      # Clean install with exact versions
      - run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install @pulumi/pulumi@3.55.0
          npm install @pulumi/aws@5.42.0

      # Install Pulumi CLI with retry logic
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2
        with:
          pulumi-version: '3.55.0'
          install-only: true

      # AWS configuration
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GithubActionRole
          aws-region: us-east-1

      # Run Pulumi with fixed plugin installation
      - name: Run Pulumi
        run: |
          export PULUMI_SKIP_UPDATE_CHECK=true
          
          # First try official download with retry
          for i in {1..3}; do
            pulumi plugin install language nodejs v3.55.0 && break || sleep 5
          done
          
          # Fallback to direct download if official fails
          if [ ! -f ~/.pulumi/plugins/pulumi-language-nodejs-v3.55.0 ]; then
            echo "Falling back to direct download..."
            mkdir -p ~/.pulumi/plugins
            curl -L https://github.com/pulumi/pulumi-nodejs/releases/download/v3.55.0/pulumi-language-nodejs-v3.55.0-linux-amd64.tar.gz | tar xz -C ~/.pulumi/plugins
            chmod +x ~/.pulumi/plugins/pulumi-language-nodejs-v3.55.0
          fi
          
          pulumi plugin install resource aws v5.42.0
          pulumi preview --stack dev --non-interactive
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}