name: Pulumi Deployment
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC
      pull-requests: write  # Only needed if PR comments are part of your workflow

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Recommended for Pulumi to get full git history

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'  # Add caching for faster builds

      - run: npm ci  # Use ci instead of install for reproducible builds
      
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GithubActionRole
          aws-region: us-east-1
          audience: sts.amazonaws.com
          role-session-name: GitHubCI-${{ github.run_id }}
          role-duration-seconds: 3600
          mask-aws-account-id: false

      # Pulumi deployment
      - uses: pulumi/actions@v3
        with:
          pulumi-version: "3.85.0"
          command: "up"
          stack-name: "dev"
          work-dir: "./"
          comment-on-pr: true  # Only if you want PR comments
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}  # Recommended if using secrets
          AWS_REGION: us-east-1