name: Pulumi Deployment
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # 1. Clean environment setup
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Use Node.js 16 (most stable with Pulumi)
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Critical change
          cache: 'npm'

      # 3. Nuclear package reinstall
      - name: Clean Install
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install @pulumi/pulumi@3.55.0
          npm install @pulumi/aws@5.42.0

      # 4. Install Pulumi CLI with EXACT version match
      - name: Install Pulumi CLI
        uses: pulumi/actions@v3
        with:
          pulumi-version: '3.55.0'  # Must match SDK version
          install-only: true

      # 5. AWS configuration
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GithubActionRole
          aws-region: us-east-1

      # 6. Run Pulumi with proper plugin syntax
      - name: Run Pulumi
        run: |
          export PULUMI_SKIP_UPDATE_CHECK=true
          pulumi plugin install resource aws v5.42.0 --reinstall  # Correct plugin syntax
          pulumi preview --stack dev --non-interactive
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}