name: Pulumi Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # CORRECTED: Use the proper Pulumi action
      - uses: pulumi/actions@v3
        with:
          pulumi-version: "latest"  # or specific version like "3.85.0"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GitHubActionsRole
          aws-region: us-east-1

      - run: npm install

      - run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - if: github.event_name == 'pull_request'
        run: pulumi preview --stack dev

      - if: github.event_name == 'push'
        run: pulumi up --yes --stack dev