name: Pulumi Deployment
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # Clean environment setup
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true  # Nuclear option: completely clean repo

      # Node.js setup with cache clearing
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          always-auth: true

      # Nuclear package installation
      - name: Clean Install Dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
          npm install --force --legacy-peer-deps
          npm rebuild

      # Pulumi CLI installation with forced version
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2
        with:
          pulumi-version: '3.85.0'
          install-only: true

      # AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GithubActionRole
          aws-region: us-east-1
          audience: sts.amazonaws.com

      # Nuclear Pulumi execution
      - name: Run Pulumi Preview
        run: |
          export PULUMI_SKIP_UPDATE_CHECK=true
          export PULUMI_HOME=/home/runner/.pulumi
          export PATH=$PATH:$PULUMI_HOME/bin
          
          # Clean Pulumi cache
          rm -rf $PULUMI_HOME/{plugins,workspaces}
          
          # Run with maximum verbosity
          pulumi preview \
            --stack dev \
            --non-interactive \
            --logtostderr \
            -v=9 2>&1 | tee pulumi.log
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          NODE_OPTIONS: "--max-old-space-size=4096"

      # Artifact for debugging
      - name: Upload Pulumi Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pulumi-debug-logs
          path: pulumi.log