name: Pulumi Deployment
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install @pulumi/pulumi@3.55.0
          npm install @pulumi/aws@5.42.0

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2
        with:
          pulumi-version: '3.55.0'
          install-only: true

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GithubActionRole
          aws-region: us-east-1

      - name: Setup Pulumi Environment
        run: |
          export PULUMI_SKIP_UPDATE_CHECK=true
          
          # Create proper plugin directory structure
          mkdir -p ~/.pulumi/plugins
          mkdir -p ~/.pulumi/bin
          
          # Copy the pulumi binary to the expected location
          cp $(which pulumi) ~/.pulumi/bin/pulumi
          chmod +x ~/.pulumi/bin/pulumi
          
          # Create the language plugin symlink
          ln -sf ~/.pulumi/bin/pulumi ~/.pulumi/plugins/pulumi-language-nodejs
          ln -sf ~/.pulumi/bin/pulumi ~/.pulumi/plugins/pulumi-language-nodejs-v3.55.0
          
          # Verify installation
          echo "Pulumi binary location: $(which pulumi)"
          echo "Plugin directory contents:"
          ls -la ~/.pulumi/plugins/
          
          # Install AWS provider
          pulumi plugin install resource aws v5.42.0

      - name: Run Pulumi Preview
        run: |
          export PATH=~/.pulumi/bin:$PATH
          pulumi preview --stack dev --non-interactive --logtostderr -v=9
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}