name: Pulumi Deployment
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Use Node.js 16 (more stable with Pulumi)
      - uses: actions/setup-node@v3
        with:
          node-version: '16'  # Critical change
          cache: 'npm'

      # Clean install with exact versions
      - run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install @pulumi/pulumi@3.55.0  # Stable version
          npm install @pulumi/aws@5.42.0     # Matching AWS provider

      # Install specific Pulumi CLI version
      - name: Install Pulumi
        uses: pulumi/action-install-pulumi-cli@v2
        with:
          pulumi-version: '3.55.0'  # Must match SDK version
          install-only: true

      # AWS configuration
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GithubActionRole
          aws-region: us-east-1

      # Run Pulumi with debug - CORRECTED VERSION
      - name: Run Pulumi
        run: |
          export PULUMI_SKIP_UPDATE_CHECK=true
          # Install Node.js language plugin (correct syntax)
          pulumi plugin install language nodejs v3.55.0 --reinstall
          # Install AWS provider plugin (matching npm package version)
          pulumi plugin install resource aws v5.42.0 --reinstall
          pulumi preview --stack dev --non-interactive --logtostderr -v=9
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}