name: Pulumi Deployment
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      
      # Explicitly install Pulumi CLI
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2
        with:
          pulumi-version: '3.85.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GithubActionRole
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Run Pulumi Preview
        run: |
          export PULUMI_SKIP_UPDATE_CHECK=true
          pulumi preview --stack dev --non-interactive
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_HOME: /home/runner/.pulumi