name: Pulumi Deployment
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js (only needed if using TypeScript/JavaScript)
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - run: npm install

      # Configure AWS credentials (OIDC)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::515880899753:role/GitHubActionsRole
          aws-region: us-east-1

      # Fixed Pulumi Action with REQUIRED command parameter
      - uses: pulumi/actions@v3
        with:
          pulumi-version: "3.85.0"  # Pinned version recommended
          command: "up"             # <<< REQUIRED parameter (can be: preview, up, destroy, refresh)
          stack-name: "dev"         # <<< Also required
          work-dir: "./"
          options: "--yes --skip-preview"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_REGION: us-east-1